config/routes.rb
Rails.application.routes.draw do
  
  get     'home'    =>  'static_pages#home'
  get                   'static_pages/about'

  get     'login'  =>   'sessions#new' 
  post    'login'  =>   'sessions#create'
  delete  'logout' =>   'sessions#destroy'

  root  'static_pages#home' 
  resources :payments
  resources :users
  
  get     'signup' => 'users#new'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  EXPENSE_NAMES = ["Mortgage", "Electric", "Gas", "Water", "Daycare"] 
  validates :amount, :user, :expense_name, presence: true
  validates :expense_name, inclusion: EXPENSE_NAMES
  validates :amount, numericality: {greater_than_or_equal_to: 0.01}
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :email, presence: true, uniqueness: true
  validates :password, presence: true 
  has_secure_password
  has_many :payments 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected 
  
  def authorize
    unless User.find_by(id: session[:user_id])
    redirect_to login_url, alert: "Please Log-In"
    end
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    #allocate new object in db?
    #save object?
    #what else?
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    
    respond_to do |format|
      if @payment.save
        format.html { redirect_to payments_path, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:expense_name, :amount, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authorize, only: :destroy
  
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    
    if user && user.authenticate( params[:session][:password]) 
      session[:user_id] = user.id
      redirect_to payments_path
    else
      redirect_to login_path, alert: "Invalid username/ password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, alert: "You have successfully logged out"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:index, :update, :destroy]
  

  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to payments_url, notice: "User #{@user.name} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to payments_url, notice: "User #{@user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-inverse">
  <nav class="container-fluid">
    <div class="navbar-header">
      <ul class="">
        <li><%= link_to "Home", home_path, class:"navbar-btn" %></li>
        <li><%= link_to "Help", "#", class:"navbar-btn" %></li>
      </ul>
    </div>
  </nav>
</header>

   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%> | Welcome to Billz App </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'layouts/header' %>
  
  <div class="container">
    <%= yield %>
  </div>
  
</body>
</html>

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expense_name %><br>
    <%= f.select :expense_name, Payment::EXPENSE_NAMES %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :name%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<% provide(:title, "Home")%>

<p id="notice"><%= notice %></p>

<h1>Household Payments</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Expense name</th>
      <th>Amount</th>
      <th>User</th>
      <th>Entered On</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.expense_name %></td>
        <td><%= number_to_currency(payment.amount) %></td>
        <td><%= payment.user.name %></td>
        <td><%= payment.created_at.to_date%></td>
        <td><%= link_to 'View', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Delete', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %><br>
<%= link_to 'Log Out', logout_path, method: :delete %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Expense name:</strong>
  <%= @payment.expense_name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>User:</strong>
  <%= @payment.user.name %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
  <% provide(:title, "Home")%>
  <body>
      <div class="jumbotron">
        <h1>Billz Payment Tracking Application</h1>
        <p class="lead">It may be a lil ghetto but it's a damn good way to keep track of expense payments. Sign up today!</p>
        
        <p class="btn-group">
          <%= link_to "Signup for the app", signup_path, class: "btn btn-default btn-lg btn-success" %>
          <%= link_to "Log in", login_path, class: "btn btn-default btn-lg" %>
        </p>
      </div>
      
      <div class="row">
        <div class="col-sm-4">
          <h2>Easily Recall Expense Payments</h2>
          <p>This is text to fill up content on the page I will rpelace it later with actual copy for the webpage to use itslef ok cool. This is text to fill up content on the page I will rpelace it later with actual copy for the webpage to use itslef ok cool.</p>
        </div>
        <div class="col-sm-4">
          <h2>Easily Recall Expense Payments</h2>
          <p>This is text to fill up content on the page I will rpelace it later with actual copy for the webpage to use itslef ok cool. This is text to fill up content on the page I will rpelace it later with actual copy for the webpage to use itslef ok cool.</p>
        </div>
        <div class="col-sm-4">
          <h2>Easily Recall Expense Payments</h2>
          <p>This is text to fill up content on the page I will rpelace it later with actual copy for the webpage to use itslef ok cool. This is text to fill up content on the page I will rpelace it later with actual copy for the webpage to use itslef ok cool.</p>
        </div>
      </div>    
      <div class="row">
        <div class="col-sm-6">
          <h3>Easily Recall Expense Payments</h3>
          <p>This is text to fill up content on the page I will rpelace it later with actual copy for the webpage to use itslef ok cool.</p>
        </div>
        <div class="col-sm-6">
          <h3>Easily Recall Expense Payments</h3>
          <p>This is text to fill up content on the page I will rpelace it later with actual copy for the webpage to use itslef ok cool.</p>
          <a href="#">Sign up for Billz</a>     
        </div>
      </div>
    </div>
  </body>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>